# Generated by Django 3.0.4 on 2020-03-16 04:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ST', 'Started'), ('FI', 'Finished'), ('SP', 'Stopped')], default='ST', max_length=2)),
                ('won', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mines', models.CharField(default='', max_length=4096, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('flags', models.CharField(default='', max_length=4096, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('rows', models.PositiveIntegerField(default=16)),
                ('columns', models.PositiveIntegerField(default=32)),
                ('added_flags', models.PositiveIntegerField(default=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Game')),
            ],
        ),
    ]
