# Generated by Django 3.0.4 on 2020-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='plays',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='flags',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='mines',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
