# Generated by Django 3.0.4 on 2020-03-17 23:06

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200317_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameboard',
            name='flags',
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='plays',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
